name: prerelease

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run build.sh
        run: sh build.sh

      - name: Delete current prerelease assets
        uses: andreaswilli/delete-release-assets-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: Prerelease
          deleteOnlyFromDrafts: false

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: Prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Prerelease
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        with:
          tag: Prerelease
          tag_name: Prerelease
          files: box4_v*.zip
          prerelease: true
          generate_release_notes: true
