name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: webui/package-lock.json

      - name: Build WebUI
        working-directory: webui
        run: |
          npm ci
          npm run build

      - name: Run build.sh
        run: sh build.sh

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: box4_v*.zip
          generate_release_notes: true
